# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: execute Ghost Inspector test
        uses: docker://ghostinspector/cli
        with:
          args: test execute 66509d573b8c989d7213cb41 \
            --apiKey ebe4caf266cbf35d234588fb0ac01ee1d62cf244 \            
            --errorOnFail
